ParksAPI2/Models/Park.cs
namespace ParksAPI2.Models
{
  public class Park
  {
    public int ParkId {get; set;}
    public string ParkName { get; set; }
    public string Size { get; set; }
    public string Description { get; set; }

    public bool Visited { get; set;}

    public int Rating { get; set; }
  }
}

ParksAPI2/Models/ParksAPI2.cs
using Microsoft.EntityFrameworkCore;

namespace ParksAPI2.Models
{
  public class ParksAPI2Context : DbContext
  {
    public ParksAPI2Context(DbContextOptions<ParksAPI2Context> options)
        :base(options)
        {

        }
        public DbSet<Park> Parks {get; set;}

        protected override void OnModelCreating(ModelBuilder builder)
        {
          builder.Entity<Park>()
          .HasData(
                            new Park { ParkId = 1, ParkName = "Drake Park", Size = "Medium", Description="Music, river, events" },
                new Park { ParkId = 2, ParkName = "Esther Short", Size = "Medium", Description="Gazebos, playground" },
                new Park { ParkId = 3, ParkName = "Mount Tabor", Size = "Large", Description="Music, Dancing, Trees" },
                new Park { ParkId = 4, ParkName = "Cottonwood", Size = "Small", Description="Beach, pavilions, grills" }
          );
        }
  }
}

ParksAPI2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ParksAPI2.Models;

namespace ParksAPI2.Controllers
{
  public class HomeController : Controller
  {
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
      _logger = logger;
    }

    public IActionResult Privacy()
    {
      return View();
    }
  }
}

ParksAPI2/Controllers/ParksController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ParksAPI2.Models;
using System.Linq;

namespace ParksAPI2.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ParksController : ControllerBase
    {
      private readonly ParksAPI2Context _db;
      public ParksController(ParksAPI2Context db)
      {
        _db = db;
      }
      [HttpGet]
      public async Task<ActionResult<IEnumerable<Park>>> Get(string parkname, string size)
      {
        var query = _db.Parks.AsQueryable();
        if (parkname != null)
        {
          query = query.Where(entry => entry.ParkName == parkname);
        }
        if (size != null)
        {
          query = query.Where(entry => entry.Size == size);
        }
        return await query.ToListAsync();
      }
    [HttpGet("{id}")]
    public async Task<ActionResult<Park>> GetPark(int id)
    {
        var park = await _db.Parks.FindAsync(id);

        if (park == null)
        {
            return NotFound();
        }

        return park;
    }

     // PUT: api/Parks/id
    [HttpPut("{id}")]
    public async Task<IActionResult> Put(int id, Park Park)
    {
        if (id != Park.ParkId)
        {
          return BadRequest();
        }

        _db.Entry(Park).State = EntityState.Modified;

        try
        {
          await _db.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
            if (!ParkExists(id))
            {
              return NotFound();
            }
            else
            {
              throw;
            }
        }

        return NoContent();
    }

    // DELETE: api/Parks/id
    [HttpDelete("{id}")]
    public async Task<IActionResult> DeletePark(int id)
    {
        var park = await _db.Parks.FindAsync(id);
        if (park == null)
        {
          return NotFound();
        }

        _db.Parks.Remove(park);
        await _db.SaveChangesAsync();

        return NoContent();
    }

    private bool ParkExists(int id)
    {
        return _db.Parks.Any(e => e.ParkId == id);
    }
  }
}

ParksAPI2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@using ParksAPI2.Models;

<h1>All Parks</h1>
<hr>

<ul>
  @foreach(Park park in Model)
{
    <p><strong>@park.ParkName</strong></p>
    <ul>
        <li>Rating: @park.Rating/10</li>
        @if(park.Visited == true)
        {
            <li>Visited!</li>
        }
        else 
        {
            <li>Not Visited Yet!</li>
        }
</ul>
}

ParksAPI2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Parks API</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Parks Client</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Parks" asp-action="Index">Parks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Parks API - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>